version: "3.7"

services:
  ts_cycle:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: ts_cycle
    expose:
      - "8088"
    ports:
      - "8088:8088"
    command: npm run start
