version: "3.7"

services:
  mfa-warez:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: mfa-warez
    expose:
      - "8088"
    ports:
      - "8088:8088"
    command: npm run start
